name: Build moonPy executables

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: [3.12]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pip install --upgrade pip pyinstaller PyQt5

    - name: Build executable with PyInstaller
      run: |
        pyinstaller moonPy.py \
          --name moonPy \
          --onefile \
          --windowed \
          --noconfirm \
          --clean \
          --paths=. \
          --hidden-import=PyQt5.QtCore \
          --hidden-import=PyQt5.QtGui \
          --hidden-import=PyQt5.QtWidgets \
          --hidden-import=PyQt5.QtPrintSupport \
          --exclude-module=PySide6

    - name: Upload Windows artifact
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: moonPy-windows.exe
        path: dist/moonPy.exe

    - name: Upload macOS artifact
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: moonPy-macos
        path: dist/moonPy

    - name: Upload Linux artifact
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: moonPy-linux
        path: dist/moonPy

