name: Build moonPy for All Platforms

on:
  push:
    tags:
      - 'v*'  # Only build when you push a version tag like v1.0.0
  workflow_dispatch:  # Also allow manual runs

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt5

      - name: Build with PyInstaller (Linux & macOS)
        if: matrix.os != 'windows-latest'
        run: |
          pyinstaller moonPy.py \
            --name moonPy \
            --onefile \
            --windowed \
            --noconfirm \
            --clean \
            --paths=. \
            --hidden-import=PyQt5.QtCore \
            --hidden-import=PyQt5.QtGui \
            --hidden-import=PyQt5.QtWidgets \
            --hidden-import=PyQt5.QtPrintSupport \
            --exclude-module=PySide6

      - name: Build with PyInstaller (Windows)
        if: matrix.os == 'windows-latest'
        run: pyinstaller moonPy.py --name moonPy --onefile --windowed --noconfirm --clean --paths=. --hidden-import=PyQt5.QtCore --hidden-import=PyQt5.QtGui --hidden-import=PyQt5.QtWidgets --hidden-import=PyQt5.QtPrintSupport --exclude-module=PySide6

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: moonPy-${{ matrix.os }}
          path: dist/moonPy*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: ./artifacts/**/*


