name: Build moonPy executables

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install pyinstaller PyQt5

      - name: Build executable
        run: pyinstaller moonPy.py --name moonPy --onefile --windowed --noconfirm --clean --paths=. --hidden-import=PyQt5.QtCore --hidden-import=PyQt5.QtGui --hidden-import=PyQt5.QtWidgets --hidden-import=PyQt5.QtPrintSupport --exclude-module=PySide6

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: moonPy-linux
          path: dist/moonPy

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install pyinstaller PyQt5

      - name: Build executable
        run: pyinstaller moonPy.py --name moonPy --onefile --windowed --noconfirm --clean --paths=. --hidden-import=PyQt5.QtCore --hidden-import=PyQt5.QtGui --hidden-import=PyQt5.QtWidgets --hidden-import=PyQt5.QtPrintSupport --exclude-module=PySide6

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: moonPy-macos
          path: dist/moonPy

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install pyinstaller PyQt5

      - name: Build executable
        run: pyinstaller moonPy.py --name moonPy --onefile --windowed --noconfirm --clean --paths=. --hidden-import=PyQt5.QtCore --hidden-import=PyQt5.QtGui --hidden-import=PyQt5.QtWidgets --hidden-import=PyQt5.QtPrintSupport --exclude-module=PySide6

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: moonPy-windows
          path: dist/moonPy.exe

